import { ExerciseDefinition, ProgressionNode } from './types';

// ============================================================
// EXERCISE REGISTRY
// Single source of truth for all exercise data
// ============================================================

export const EXERCISE_REGISTRY: Record<string, ExerciseDefinition> = {

  // ─── VERTICAL PULL FAMILY ───────────────────────────────────────────────────
  'dead_hang': {
    id: 'dead_hang', name: 'Dead Hang',
    category: 'isometric', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 1,
    progressionFamily: 'vertical_pull', progressionLevel: 1,
    progressionId: 'scapular_pull',
    repRange: [1, 1], holdRange: [10, 60], restRange: [30, 60],
    skillRequirements: [],
    coachingCues: ['Relax shoulders — let them rise toward ears', 'Full grip, thumb wrapped around bar', 'Body perfectly still — no swinging', 'Breathe deep and slow'],
    breathingCue: 'Deep belly breaths throughout — stay relaxed',
    modifications: ['Use a chair for partial weight support'],
    commonMistakes: ['Engaging shoulders instead of relaxing them', 'Swinging body', 'Gripping too hard and tensing everything'],
    tips: ['This decompresses your spine', 'Build to 60s before moving to scapular pulls', 'Most underrated exercise in calisthenics'],
  },

  'scapular_pull': {
    id: 'scapular_pull', name: 'Scapular Pull-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: [],
    equipment: ['pull-up bar'], difficulty: 2,
    progressionFamily: 'vertical_pull', progressionLevel: 2,
    regressionId: 'dead_hang', progressionId: 'negative_pullup',
    repRange: [5, 15], restRange: [45, 90],
    skillRequirements: ['dead_hang_30s'],
    coachingCues: ['Hang dead', 'Pull shoulder blades DOWN without bending arms', 'Hold 1s at top', 'Lower with control'],
    breathingCue: 'Exhale as you retract shoulder blades',
    modifications: ['Reduce range of motion'],
    commonMistakes: ['Bending elbows', 'Not achieving full retraction at top'],
    tips: ['This activates lats for full pull-ups', 'Critical foundation movement'],
  },

  'negative_pullup': {
    id: 'negative_pullup', name: 'Negative Pull-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 3,
    progressionFamily: 'vertical_pull', progressionLevel: 3,
    regressionId: 'scapular_pull', progressionId: 'pullup',
    repRange: [3, 8], restRange: [60, 120],
    skillRequirements: ['scapular_pull'],
    coachingCues: ['Jump or step to top position — chin above bar', 'Lower as slowly as possible — aim 5-8 seconds', 'Full extension at bottom before dropping', 'Stay controlled throughout'],
    breathingCue: 'Inhale slowly and continuously as you lower',
    modifications: ['3-second negatives to start'],
    commonMistakes: ['Dropping too fast', 'Not reaching full extension at bottom', 'Kipping up instead of jumping/stepping'],
    tips: ['Fastest way to build pull-up strength', 'The lowering builds as much strength as pulling'],
  },

  'pullup': {
    id: 'pullup', name: 'Pull-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 5,
    progressionFamily: 'vertical_pull', progressionLevel: 4,
    regressionId: 'negative_pullup', progressionId: 'chest_to_bar',
    repRange: [1, 20], restRange: [60, 120],
    skillRequirements: ['negative_pullup'],
    coachingCues: ['Dead hang start — arms fully straight', 'Drive elbows DOWN toward hips — not backward', 'Chest rises toward bar', 'Squeeze shoulder blades at top', 'Lower 3 seconds — resist gravity'],
    breathingCue: 'Exhale pulling up, inhale lowering',
    modifications: ['Negative pull-ups', 'Assisted with band'],
    commonMistakes: ['Swinging for momentum', 'Not reaching full extension', 'Pulling with arms not back', 'Kipping'],
    tips: ['Imagine putting elbows in back pockets', 'Dead hang every single rep'],
  },

  'chinup': {
    id: 'chinup', name: 'Chin-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 4,
    progressionFamily: 'vertical_pull', progressionLevel: 4,
    regressionId: 'negative_pullup', progressionId: 'chest_to_bar',
    repRange: [1, 20], restRange: [60, 120],
    skillRequirements: ['negative_pullup'],
    coachingCues: ['Supinated (underhand) grip shoulder-width', 'Lead with chest rising toward bar', 'Full extension at bottom each rep', 'Keep core tight throughout'],
    breathingCue: 'Exhale pulling up, inhale lowering',
    modifications: ['Assisted with resistance band'],
    commonMistakes: ['Flaring elbows', 'Kipping', 'Not full extension at bottom'],
    tips: ['More bicep-focused than pull-ups', 'Great complement — do both'],
  },

  'chest_to_bar': {
    id: 'chest_to_bar', name: 'Chest-to-Bar Pull-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 7,
    progressionFamily: 'vertical_pull', progressionLevel: 5,
    regressionId: 'pullup', progressionId: 'explosive_pullup',
    repRange: [1, 10], restRange: [90, 120],
    skillRequirements: ['pullup_10reps'],
    coachingCues: ['Lean back slightly to allow chest contact', 'Full dead hang start', 'Drive elbows down and back hard', 'Chest must touch bar'],
    breathingCue: 'Exhale driving up, inhale lowering',
    modifications: ['High pull-ups with chin well above bar'],
    commonMistakes: ['Not actually touching chest to bar', 'Kipping', 'Incomplete range of motion'],
    tips: ['Requires serious lat strength', 'Step between pull-up and explosive work'],
  },

  'explosive_pullup': {
    id: 'explosive_pullup', name: 'Explosive Pull-ups',
    category: 'strength', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 8,
    progressionFamily: 'vertical_pull', progressionLevel: 6,
    regressionId: 'chest_to_bar', progressionId: 'typewriter_pullup',
    repRange: [1, 8], restRange: [90, 150],
    skillRequirements: ['chest_to_bar_5reps'],
    coachingCues: ['Dead hang start every rep', 'Pull with maximum intent — aim to get chest to bar', 'Hands can briefly leave bar at top', 'Control the negative slowly'],
    breathingCue: 'Exhale explosively on the pull',
    modifications: ['Fast regular pull-ups'],
    commonMistakes: ['Insufficient base strength', 'Rushing without power', 'Ignoring the negative'],
    tips: ['Quality over quantity', 'Fast twitch fiber development'],
  },

  'typewriter_pullup': {
    id: 'typewriter_pullup', name: 'Typewriter Pull-ups',
    category: 'skill', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 9,
    progressionFamily: 'vertical_pull', progressionLevel: 7,
    regressionId: 'explosive_pullup', progressionId: 'archer_pullup',
    repRange: [1, 5], restRange: [120, 180],
    skillRequirements: ['explosive_pullup_5reps'],
    coachingCues: ['Wide grip dead hang', 'Pull to chest height', 'Shift body side to side at top', 'One arm nearly extends as you move laterally', 'Return center before lowering'],
    breathingCue: 'Inhale at dead hang, exhale pulling',
    modifications: ['Regular wide grip pull-ups'],
    commonMistakes: ['Attempting without sufficient pull-up base', 'Rushing the lateral movement'],
    tips: ['Builds toward one-arm pull-up', 'Takes months of pull-up practice to access'],
  },

  'archer_pullup': {
    id: 'archer_pullup', name: 'Archer Pull-ups',
    category: 'skill', movement: 'vertical_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar'], difficulty: 9,
    progressionFamily: 'vertical_pull', progressionLevel: 8,
    regressionId: 'typewriter_pullup',
    repRange: [1, 5], restRange: [120, 180],
    skillRequirements: ['typewriter_pullup_3reps'],
    coachingCues: ['Wide grip', 'Pull to one side — working arm fully bent, other nearly straight', 'Control the return', 'Alternate sides'],
    breathingCue: 'Exhale pulling toward working side',
    modifications: ['Typewriter pull-ups'],
    commonMistakes: ['Insufficient unilateral strength', 'Losing control on straight arm'],
    tips: ['Final step before one-arm pull-up progressions'],
  },

  // ─── HORIZONTAL PULL FAMILY ─────────────────────────────────────────────────
  'backpack_rows': {
    id: 'backpack_rows', name: 'Backpack Rows',
    category: 'strength', movement: 'horizontal_pull',
    primaryMuscles: ['pull'], secondaryMuscles: ['core'],
    equipment: ['backpack', 'pull-up bar'], difficulty: 3,
    progressionFamily: 'horizontal_pull', progressionLevel: 1,
    repRange: [8, 20], restRange: [60, 90],
    skillRequirements: [],
    coachingCues: ['Load backpack with books for resistance', 'Keep back flat — no rounding', 'Pull to lower chest/upper abs', 'Pause 1 second at top', 'Control the lowering'],
    breathingCue: 'Exhale on the pull, inhale releasing',
    modifications: ['Use lighter load or bodyweight only'],
    commonMistakes: ['Rounding back', 'Using momentum', 'Not pausing at top'],
    tips: ['Increase weight progressively', 'Great horizontal pull builder'],
  },

  // ─── HORIZONTAL PUSH FAMILY ─────────────────────────────────────────────────
  'incline_pushup': {
    id: 'incline_pushup', name: 'Incline Push-ups',
    category: 'strength', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: ['wall or elevated surface'], difficulty: 1,
    progressionFamily: 'horizontal_push', progressionLevel: 1,
    progressionId: 'pushup',
    repRange: [10, 30], restRange: [45, 60],
    skillRequirements: [],
    coachingCues: ['Hands on wall or elevated surface', 'Body in straight line', 'Elbows at 45° — not flared', 'Full range of motion'],
    breathingCue: 'Inhale lowering, exhale pressing',
    modifications: ['Higher incline = easier'],
    commonMistakes: ['Piking hips', 'Elbows flaring 90°'],
    tips: ['Reduce incline height over time to progress'],
  },

  'pushup': {
    id: 'pushup', name: 'Push-ups',
    category: 'strength', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 3,
    progressionFamily: 'horizontal_push', progressionLevel: 2,
    regressionId: 'incline_pushup', progressionId: 'diamond_pushup',
    repRange: [5, 30], restRange: [45, 90],
    skillRequirements: [],
    coachingCues: ['Hands just outside shoulder width', 'Elbows at 45° to body', 'Full range — chest nearly touches floor', 'Body rigid like a plank', 'Squeeze chest at top'],
    breathingCue: 'Inhale down, exhale up',
    modifications: ['Knee push-ups'],
    commonMistakes: ['Elbows flaring out 90°', 'Hips sagging', 'Not reaching full depth', 'Looking up'],
    tips: ['Control the negative', 'Spread fingers wide for stability'],
  },

  'diamond_pushup': {
    id: 'diamond_pushup', name: 'Diamond Push-ups',
    category: 'strength', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 5,
    progressionFamily: 'horizontal_push', progressionLevel: 3,
    regressionId: 'pushup', progressionId: 'decline_pushup',
    repRange: [5, 20], restRange: [60, 90],
    skillRequirements: ['pushup_15reps'],
    coachingCues: ['Hands form diamond shape under chest', 'Elbows track back along sides', 'Keep hips level', 'Slower tempo = more tricep burn'],
    breathingCue: 'Inhale lowering, exhale pressing',
    modifications: ['Hands slightly wider if wrists hurt'],
    commonMistakes: ['Elbows flaring', 'Hips sagging or piking'],
    tips: ['Primary tricep builder', 'Complement with wider push variations'],
  },

  'decline_pushup': {
    id: 'decline_pushup', name: 'Decline Push-ups',
    category: 'strength', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: ['chair or elevated surface'], difficulty: 5,
    progressionFamily: 'horizontal_push', progressionLevel: 3,
    regressionId: 'pushup', progressionId: 'archer_pushup',
    repRange: [5, 20], restRange: [60, 90],
    skillRequirements: ['pushup_15reps'],
    coachingCues: ['Feet elevated on chair/bed', 'Keep body in straight line', 'Elbows at 45° — not flared', 'Lower chest toward floor not face'],
    breathingCue: 'Inhale lowering, exhale pressing',
    modifications: ['Standard push-ups'],
    commonMistakes: ['Hips piking up', 'Not keeping straight line'],
    tips: ['Targets upper chest and front delts', 'Builds toward handstand push-up path'],
  },

  'archer_pushup': {
    id: 'archer_pushup', name: 'Archer Push-ups',
    category: 'strength', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 7,
    progressionFamily: 'horizontal_push', progressionLevel: 4,
    regressionId: 'decline_pushup', progressionId: 'pseudo_planche_pushup',
    repRange: [3, 10], restRange: [90, 120],
    skillRequirements: ['pushup_20reps'],
    coachingCues: ['Wide stance, one arm straight as you shift weight', 'Working arm does full push-up range', 'Extended arm stays straight as support', 'Progress by reducing support from straight arm'],
    breathingCue: 'Inhale shifting down, exhale pressing',
    modifications: ['Stay wider for more support', 'Less weight shift to reduce difficulty'],
    commonMistakes: ['Extended arm bending', 'Not getting wide enough'],
    tips: ['Bridge to one-arm push-up', 'Gradually reduce support of straight arm'],
  },

  'pseudo_planche_pushup': {
    id: 'pseudo_planche_pushup', name: 'Pseudo Planche Push-ups',
    category: 'skill', movement: 'horizontal_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 8,
    progressionFamily: 'horizontal_push', progressionLevel: 5,
    regressionId: 'archer_pushup',
    repRange: [3, 10], restRange: [90, 150],
    skillRequirements: ['archer_pushup_5reps'],
    coachingCues: ['Hands pointing backward beside hips', 'Lean forward until shoulders over or past hands', 'Body stays rigid like a board', 'Start with less lean — build over weeks'],
    breathingCue: 'Inhale lowering, exhale pressing',
    modifications: ['Standard push-ups with slight forward lean'],
    commonMistakes: ['Too much lean too soon', 'Elbows flaring', 'Hips dropping'],
    tips: ['Foundation for the planche skill', 'Every rep brings you closer to elite gymnastics'],
  },

  'clap_pushup': {
    id: 'clap_pushup', name: 'Clap Push-ups',
    category: 'strength', movement: 'explosive',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 7,
    progressionFamily: 'explosive_push', progressionLevel: 1,
    repRange: [3, 10], restRange: [90, 120],
    skillRequirements: ['pushup_20reps'],
    coachingCues: ['Push explosively off the floor', 'Clap hands quickly at top', 'Land with arms slightly bent — never locked', 'Build on solid push-up base first'],
    breathingCue: 'Exhale explosively off the floor',
    modifications: ['Push hard without clapping first'],
    commonMistakes: ['Landing with locked arms', 'Insufficient base strength', 'Losing form after rep 3'],
    tips: ['Fast twitch chest development', 'Land soft'],
  },

  // ─── VERTICAL PUSH (SHOULDER) FAMILY ────────────────────────────────────────
  'pike_pushup': {
    id: 'pike_pushup', name: 'Pike Push-ups',
    category: 'strength', movement: 'vertical_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 4,
    progressionFamily: 'vertical_push', progressionLevel: 1,
    progressionId: 'elevated_pike_pushup',
    repRange: [5, 15], restRange: [60, 90],
    skillRequirements: [],
    coachingCues: ['Inverted V position — hips as high as possible', 'Lower head between hands toward floor', 'Elbows flare outward (unlike regular push-ups)', 'Press back up to inverted V'],
    breathingCue: 'Inhale down, exhale press',
    modifications: ['Elevated pike with hands on chair'],
    commonMistakes: ['Hips not high enough', 'Head going in front of hands instead of between', 'Elbows flaring too extremely'],
    tips: ['Path to handstand push-ups', 'Higher hips = more shoulder focus'],
  },

  'elevated_pike_pushup': {
    id: 'elevated_pike_pushup', name: 'Elevated Pike Push-ups',
    category: 'strength', movement: 'vertical_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: ['chair or elevated surface'], difficulty: 6,
    progressionFamily: 'vertical_push', progressionLevel: 2,
    regressionId: 'pike_pushup', progressionId: 'handstand_wall_hold',
    repRange: [3, 12], restRange: [60, 120],
    skillRequirements: ['pike_pushup_10reps'],
    coachingCues: ['Feet elevated on chair', 'Body in more vertical line than regular pike', 'Head between hands at bottom', 'Full range of motion'],
    breathingCue: 'Inhale down, exhale press',
    modifications: ['Lower foot elevation'],
    commonMistakes: ['Not achieving full vertical angle'],
    tips: ['Closer to handstand push-up mechanics'],
  },

  'handstand_wall_hold': {
    id: 'handstand_wall_hold', name: 'Handstand Wall Holds',
    category: 'skill', movement: 'vertical_push',
    primaryMuscles: ['push'], secondaryMuscles: ['core'],
    equipment: ['wall'], difficulty: 7,
    progressionFamily: 'vertical_push', progressionLevel: 3,
    regressionId: 'elevated_pike_pushup',
    repRange: [1, 1], holdRange: [10, 60], restRange: [90, 120],
    skillRequirements: ['elevated_pike_pushup_8reps'],
    coachingCues: ['Kick up to wall with control', 'Stack wrists, elbows, shoulders in line', 'Look between hands — slightly forward', 'Squeeze glutes to keep hips over hands', 'Spread fingers wide — press into all fingers'],
    breathingCue: 'Slow controlled breaths — stay calm',
    modifications: ['Pike hold with feet on wall facing wall'],
    commonMistakes: ['Banana shape (hips sagging) — squeeze glutes', 'Looking up at wall', 'Arms bending'],
    tips: ['Build to 60s holds', 'Foundation for freestanding handstand'],
  },

  // ─── DIPS ───────────────────────────────────────────────────────────────────
  'chair_dips': {
    id: 'chair_dips', name: 'Chair Dips',
    category: 'strength', movement: 'vertical_push',
    primaryMuscles: ['push'], secondaryMuscles: [],
    equipment: ['chair'], difficulty: 3,
    progressionFamily: 'dip', progressionLevel: 1,
    progressionId: 'dips',
    repRange: [8, 20], restRange: [60, 90],
    skillRequirements: [],
    coachingCues: ['Hands grip edge of sturdy chair', 'Lower until upper arms parallel to floor', 'Keep elbows pointing back not flared', 'Straighten arms fully at top'],
    breathingCue: 'Inhale dipping, exhale pressing up',
    modifications: ['Reduce range of motion'],
    commonMistakes: ['Elbows flaring to sides', 'Not reaching full depth'],
    tips: ['Excellent tricep builder', 'Control every rep'],
  },

  'dips': {
    id: 'dips', name: 'Dips',
    category: 'strength', movement: 'vertical_push',
    primaryMuscles: ['push'], secondaryMuscles: [],
    equipment: ['parallel bars or two chairs'], difficulty: 6,
    progressionFamily: 'dip', progressionLevel: 2,
    regressionId: 'chair_dips',
    repRange: [5, 20], restRange: [60, 120],
    skillRequirements: ['chair_dips_15reps'],
    coachingCues: ['Use two sturdy chairs or parallel bars', 'Lower until 90° at elbows', 'Lean slightly forward for more chest emphasis', 'Full lockout at top'],
    breathingCue: 'Inhale dipping, exhale pressing',
    modifications: ['Chair dips'],
    commonMistakes: ['Not reaching 90°', 'Elbows flaring', 'Shrugging shoulders'],
    tips: ['One of the best upper body mass builders in calisthenics'],
  },

  // ─── SQUAT FAMILY ───────────────────────────────────────────────────────────
  'bodyweight_squat': {
    id: 'bodyweight_squat', name: 'Squats',
    category: 'strength', movement: 'squat',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 2,
    progressionFamily: 'squat', progressionLevel: 1,
    progressionId: 'bulgarian_split_squat',
    repRange: [10, 30], restRange: [45, 90],
    skillRequirements: [],
    coachingCues: ['Feet shoulder-width, toes slightly out', 'Break at hips and knees simultaneously', 'Keep chest tall — do not lean forward', 'Drive knees out over toes', 'Thighs parallel to floor or below'],
    breathingCue: 'Inhale going down, exhale driving up',
    modifications: ['Sit to chair and stand'],
    commonMistakes: ['Knees caving inward', 'Chest collapsing forward', 'Not reaching depth', 'Heels rising off floor'],
    tips: ['Drive through heels', 'Squeeze glutes at top'],
  },

  'jump_squat': {
    id: 'jump_squat', name: 'Jump Squats',
    category: 'strength', movement: 'explosive',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 4,
    progressionFamily: 'explosive_legs', progressionLevel: 1,
    repRange: [8, 20], restRange: [60, 90],
    skillRequirements: ['bodyweight_squat_20reps'],
    coachingCues: ['Land softly — toe-heel-heel', 'Immediately descend on landing', 'Arms drive up for extra height', 'Land with slight knee bend'],
    breathingCue: 'Exhale explosively on the jump',
    modifications: ['Regular squats with fast tempo'],
    commonMistakes: ['Landing stiff-legged', 'Going too fast and losing form'],
    tips: ['Focus on landing mechanics as much as jumping'],
  },

  'split_squat': {
    id: 'split_squat', name: 'Split Squats',
    category: 'strength', movement: 'squat',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 3,
    progressionFamily: 'squat', progressionLevel: 2,
    regressionId: 'bodyweight_squat', progressionId: 'bulgarian_split_squat',
    repRange: [8, 15], restRange: [60, 90],
    skillRequirements: [],
    coachingCues: ['Split stance — one foot forward, one back', 'Lower back knee toward floor', 'Front knee tracks over toes', 'Drive through front heel to stand'],
    breathingCue: 'Inhale descending, exhale rising',
    modifications: ['Hold onto wall for balance'],
    commonMistakes: ['Front knee caving', 'Leaning too far forward'],
    tips: ['Great stepping stone to Bulgarian and pistol'],
  },

  'bulgarian_split_squat': {
    id: 'bulgarian_split_squat', name: 'Bulgarian Split Squats',
    category: 'strength', movement: 'squat',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: ['chair or elevated surface'], difficulty: 6,
    progressionFamily: 'squat', progressionLevel: 3,
    regressionId: 'split_squat', progressionId: 'assisted_pistol',
    repRange: [6, 12], restRange: [60, 120],
    skillRequirements: ['split_squat_12reps'],
    coachingCues: ['Rear foot elevated on chair/bed — top of foot down', 'Front foot far enough forward — knee stays behind toes', 'Drop straight DOWN not forward', 'Drive through front heel', 'Keep torso upright'],
    breathingCue: 'Inhale descending, exhale rising',
    modifications: ['Regular reverse lunges'],
    commonMistakes: ['Front foot too close — knee shoots past toes', 'Leaning too far forward', 'Driving through toes instead of heel'],
    tips: ['Most effective single-leg strength exercise', 'Expect weak side to really struggle'],
  },

  'assisted_pistol': {
    id: 'assisted_pistol', name: 'Assisted Pistol Squats',
    category: 'strength', movement: 'squat',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: ['pull-up bar for assistance'], difficulty: 7,
    progressionFamily: 'squat', progressionLevel: 4,
    regressionId: 'bulgarian_split_squat', progressionId: 'pistol_squat',
    repRange: [3, 8], restRange: [90, 120],
    skillRequirements: ['bulgarian_split_squat_10reps'],
    coachingCues: ['Hold pull-up bar for balance', 'One leg extended forward', 'Squat down on standing leg', 'Drive through heel', 'Reduce bar assistance progressively'],
    breathingCue: 'Inhale descending, exhale driving up',
    modifications: ['Use more bar assistance'],
    commonMistakes: ['Heel rising off floor — ankle flexibility issue', 'Knee caving inward'],
    tips: ['Work ankle flexibility daily to improve', 'Reduce assistance gradually over weeks'],
  },

  'pistol_squat': {
    id: 'pistol_squat', name: 'Pistol Squats',
    category: 'skill', movement: 'squat',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 8,
    progressionFamily: 'squat', progressionLevel: 5,
    regressionId: 'assisted_pistol',
    repRange: [3, 8], restRange: [90, 150],
    skillRequirements: ['assisted_pistol_5reps'],
    coachingCues: ['Stand on one leg', 'Other leg extended forward', 'Descend to full depth on standing leg', 'Drive through heel — not toes', 'Build depth week by week'],
    breathingCue: 'Inhale descending, exhale driving up',
    modifications: ['Assisted pistol holding bar'],
    commonMistakes: ['Heel rising — ankle flexibility', 'Knee caving', 'Extended leg touching floor'],
    tips: ['Demonstrates elite single-leg strength', 'Full pistol takes months of practice'],
  },

  'jump_lunge': {
    id: 'jump_lunge', name: 'Jump Lunges',
    category: 'strength', movement: 'explosive',
    primaryMuscles: ['legs'], secondaryMuscles: ['core'],
    equipment: [], difficulty: 5,
    progressionFamily: 'explosive_legs', progressionLevel: 2,
    repRange: [6, 16], restRange: [60, 90],
    skillRequirements: ['jump_squat_12reps'],
    coachingCues: ['Switch legs in the air', 'Land softly in split stance', 'Keep torso upright throughout', 'Drive back knee toward floor'],
    breathingCue: 'Exhale on the explosive jump',
    modifications: ['Alternating reverse lunges'],
    commonMistakes: ['Landing stiff', 'Knees caving on landing'],
    tips: ['High calorie burn + leg power development'],
  },

  // ─── CORE FAMILY ────────────────────────────────────────────────────────────
  'plank': {
    id: 'plank', name: 'Plank',
    category: 'isometric', movement: 'isometric',
    primaryMuscles: ['core'], secondaryMuscles: ['push'],
    equipment: [], difficulty: 3,
    progressionFamily: 'core', progressionLevel: 2,
    progressionId: 'hollow_hold',
    repRange: [1, 1], holdRange: [20, 120], restRange: [45, 90],
    skillRequirements: [],
    coachingCues: ['Straight line from head to heels', 'Squeeze glutes and quads HARD', 'Brace core — imagine a punch coming', 'Gaze slightly ahead of hands', 'Never hold your breath'],
    breathingCue: 'Slow controlled breaths throughout',
    modifications: ['Knee plank'],
    commonMistakes: ['Hips sagging', 'Hips piking up', 'Holding breath', 'Head drooping'],
    tips: ['Activation matters more than duration', 'If hips drop — squeeze glutes harder'],
  },

  'hollow_hold': {
    id: 'hollow_hold', name: 'Hollow Hold',
    category: 'isometric', movement: 'isometric',
    primaryMuscles: ['core'], secondaryMuscles: [],
    equipment: [], difficulty: 5,
    progressionFamily: 'core', progressionLevel: 3,
    regressionId: 'plank', progressionId: 'hanging_knee_raise',
    repRange: [1, 1], holdRange: [15, 60], restRange: [45, 90],
    skillRequirements: ['plank_45s'],
    coachingCues: ['Lie flat on back', 'Press lower back INTO floor — no gap at all', 'Raise legs to ~45°', 'Raise shoulders off floor', 'Extend arms overhead', 'Body forms banana shape'],
    breathingCue: 'Exhale fully, maintain core brace, breathe controlled',
    modifications: ['Arms by sides, or knees tucked'],
    commonMistakes: ['Lower back arching off floor — raise legs higher', 'Holding breath', 'Bending knees when not needed'],
    tips: ['Foundation of ALL calisthenics skills', 'Master this and everything gets easier'],
  },

  'hanging_knee_raise': {
    id: 'hanging_knee_raise', name: 'Hanging Knee Raises',
    category: 'strength', movement: 'isometric',
    primaryMuscles: ['core'], secondaryMuscles: ['pull'],
    equipment: ['pull-up bar'], difficulty: 4,
    progressionFamily: 'core', progressionLevel: 4,
    regressionId: 'hollow_hold', progressionId: 'hanging_leg_raise',
    repRange: [8, 20], restRange: [45, 90],
    skillRequirements: ['dead_hang_20s'],
    coachingCues: ['Dead hang from bar', 'Control the swing — stay still', 'Tuck knees to chest at top', 'Lower slowly — resist gravity', 'Progress to straight leg raises'],
    breathingCue: 'Exhale raising knees, inhale lowering',
    modifications: ['Small range raises to start'],
    commonMistakes: ['Swinging body', 'Dropping legs fast'],
    tips: ['No swinging — that is cheating'],
  },

  'hanging_leg_raise': {
    id: 'hanging_leg_raise', name: 'Hanging Leg Raises',
    category: 'strength', movement: 'isometric',
    primaryMuscles: ['core'], secondaryMuscles: ['pull'],
    equipment: ['pull-up bar'], difficulty: 6,
    progressionFamily: 'core', progressionLevel: 5,
    regressionId: 'hanging_knee_raise', progressionId: 'lsit',
    repRange: [5, 15], restRange: [60, 90],
    skillRequirements: ['hanging_knee_raise_12reps'],
    coachingCues: ['No swinging — control the movement', 'Tilt pelvis backward at the top', 'Lower slowly — 3 seconds down', 'Keep legs straight for full difficulty'],
    breathingCue: 'Exhale raising legs, inhale lowering',
    modifications: ['Bent-knee raises'],
    commonMistakes: ['Swinging for momentum', 'Not tilting pelvis at top', 'Dropping legs fast'],
    tips: ['Tilt pelvis at top for maximum ab activation'],
  },

  'lsit': {
    id: 'lsit', name: 'L-Sit Progression',
    category: 'skill', movement: 'isometric',
    primaryMuscles: ['core'], secondaryMuscles: ['push'],
    equipment: ['two chairs or parallel bars'], difficulty: 8,
    progressionFamily: 'core', progressionLevel: 6,
    regressionId: 'hanging_leg_raise',
    repRange: [1, 1], holdRange: [3, 30], restRange: [90, 120],
    skillRequirements: ['hanging_leg_raise_10reps'],
    coachingCues: ['Between two chairs — press DOWN hard into chairs', 'Elevate hips off floor first', 'One leg extended then both', 'Lean slightly forward — shifts weight over hands', 'Exhale and brace core maximally'],
    breathingCue: 'Exhale and brace core hard',
    modifications: ['Tuck L-sit with both knees bent'],
    commonMistakes: ['Not pressing down hard enough', 'Hips dropping immediately', 'Bent legs before ready'],
    tips: ['5 seconds is harder than it looks', 'Takes months to achieve — start today'],
  },

  // ─── CONDITIONING ───────────────────────────────────────────────────────────
  'mountain_climbers': {
    id: 'mountain_climbers', name: 'Mountain Climbers',
    category: 'conditioning', movement: 'explosive',
    primaryMuscles: ['core', 'full'], secondaryMuscles: ['push'],
    equipment: [], difficulty: 3,
    progressionFamily: 'conditioning', progressionLevel: 1,
    repRange: [1, 1], holdRange: [20, 60], restRange: [30, 60],
    skillRequirements: [],
    coachingCues: ['Hips level — do not let them rise', 'Fast but controlled knee drives', 'Shoulders over wrists throughout', 'Core braced the entire time'],
    breathingCue: 'Rhythmic — exhale each knee drive',
    modifications: ['Slow mountain climbers'],
    commonMistakes: ['Hips rising', 'Losing core tension'],
    tips: ['Rhythm matters — find your pace and keep it'],
  },

  'burpee': {
    id: 'burpee', name: 'Burpees',
    category: 'conditioning', movement: 'explosive',
    primaryMuscles: ['full'], secondaryMuscles: [],
    equipment: [], difficulty: 5,
    progressionFamily: 'conditioning', progressionLevel: 2,
    repRange: [5, 20], restRange: [60, 120],
    skillRequirements: ['pushup_5reps'],
    coachingCues: ['Chest must touch floor each rep', 'Explosive jump with arms overhead', 'Keep steady rhythm over speed', 'Breathe — never hold your breath'],
    breathingCue: 'Exhale on jump, inhale dropping down',
    modifications: ['Step back/forward instead of jumping', 'Remove push-up'],
    commonMistakes: ['Chest not touching floor', 'No jump at top', 'Going too fast and losing form'],
    tips: ['Most hated — most effective', 'Consistent pace beats sprinting and dying'],
  },

  // ─── ISOMETRIC ──────────────────────────────────────────────────────────────
  'wall_sit': {
    id: 'wall_sit', name: 'Wall Sit',
    category: 'isometric', movement: 'isometric',
    primaryMuscles: ['legs'], secondaryMuscles: [],
    equipment: ['wall'], difficulty: 3,
    progressionFamily: 'isometric_legs', progressionLevel: 1,
    repRange: [1, 1], holdRange: [20, 120], restRange: [45, 90],
    skillRequirements: [],
    coachingCues: ['90° at knees — thighs parallel to floor', 'Back flat against wall the whole time', 'Do not rest hands on thighs', 'Focus on slow controlled breathing'],
    breathingCue: 'Deep rhythmic breaths — stay calm',
    modifications: ['Higher angle (less than 90°)'],
    commonMistakes: ['Thighs above parallel', 'Knees past toes', 'Pushing on thighs with hands'],
    tips: ['When quads burn — breathe and focus elsewhere', 'Box breathing 4-4-4-4 helps'],
  },
};

// ─── LOOKUP HELPERS ───────────────────────────────────────────────────────────
export function getExercise(id: string): ExerciseDefinition | undefined {
  return EXERCISE_REGISTRY[id];
}

export function getExerciseByName(name: string): ExerciseDefinition | undefined {
  return Object.values(EXERCISE_REGISTRY).find(e => e.name === name);
}

export function getProgressionFamily(family: string): ExerciseDefinition[] {
  return Object.values(EXERCISE_REGISTRY)
    .filter(e => e.progressionFamily === family)
    .sort((a, b) => a.progressionLevel - b.progressionLevel);
}

export function getNextProgression(exerciseId: string): ExerciseDefinition | undefined {
  const ex = EXERCISE_REGISTRY[exerciseId];
  if (!ex?.progressionId) return undefined;
  return EXERCISE_REGISTRY[ex.progressionId];
}

export function getRegression(exerciseId: string): ExerciseDefinition | undefined {
  const ex = EXERCISE_REGISTRY[exerciseId];
  if (!ex?.regressionId) return undefined;
  return EXERCISE_REGISTRY[ex.regressionId];
}

// ─── NAME TO ID MAP (for migration from old name-based system) ────────────────
export const EXERCISE_NAME_TO_ID: Record<string, string> = {
  'Pull-ups': 'pullup',
  'Chin-ups': 'chinup',
  'Backpack rows': 'backpack_rows',
  'Dead hangs': 'dead_hang',
  'Hanging leg raises': 'hanging_leg_raise',
  'Hanging knee raises': 'hanging_knee_raise',
  'Negative pull-ups': 'negative_pullup',
  'Explosive pull-ups': 'explosive_pullup',
  'Chest-to-bar pull-ups': 'chest_to_bar',
  'Typewriter pull-ups': 'typewriter_pullup',
  'Squats': 'bodyweight_squat',
  'Jump squats': 'jump_squat',
  'Bulgarian split squats': 'bulgarian_split_squat',
  'Wall sit': 'wall_sit',
  'Mountain climbers': 'mountain_climbers',
  'Decline push-ups': 'decline_pushup',
  'Pike push-ups': 'pike_pushup',
  'Chair dips': 'chair_dips',
  'Diamond push-ups': 'diamond_pushup',
  'Plank': 'plank',
  'Hollow hold': 'hollow_hold',
  'Burpees': 'burpee',
  'Push-ups': 'pushup',
  'Jump lunges': 'jump_lunge',
  'Archer push-ups': 'archer_pushup',
  'Clap push-ups': 'clap_pushup',
  'Pseudo planche push-ups': 'pseudo_planche_pushup',
  'L-sit progression': 'lsit',
  'Handstand wall holds': 'handstand_wall_hold',
  'Dips': 'dips',
  'Pistol squat progression': 'pistol_squat',
};

// ─── PROGRESSION TREE ─────────────────────────────────────────────────────────
export const PROGRESSION_TREE: Record<string, ProgressionNode> = {
  dead_hang: {
    exerciseId: 'dead_hang',
    children: ['scapular_pull'],
    unlockCriteria: {},
    masteryThreshold: { duration: 30, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  scapular_pull: {
    exerciseId: 'scapular_pull',
    parent: 'dead_hang',
    children: ['negative_pullup'],
    unlockCriteria: { minDuration: 30 },
    masteryThreshold: { reps: 12, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  negative_pullup: {
    exerciseId: 'negative_pullup',
    parent: 'scapular_pull',
    children: ['pullup', 'chinup'],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { reps: 5, consecutiveSessions: 4, difficultyTag: 'good' },
  },
  pullup: {
    exerciseId: 'pullup',
    parent: 'negative_pullup',
    children: ['chest_to_bar'],
    unlockCriteria: { minReps: 3 },
    masteryThreshold: { reps: 10, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  chinup: {
    exerciseId: 'chinup',
    parent: 'negative_pullup',
    children: ['chest_to_bar'],
    unlockCriteria: { minReps: 3 },
    masteryThreshold: { reps: 10, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  chest_to_bar: {
    exerciseId: 'chest_to_bar',
    parent: 'pullup',
    children: ['explosive_pullup'],
    unlockCriteria: { minReps: 10 },
    masteryThreshold: { reps: 5, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  explosive_pullup: {
    exerciseId: 'explosive_pullup',
    parent: 'chest_to_bar',
    children: ['typewriter_pullup'],
    unlockCriteria: { minReps: 5 },
    masteryThreshold: { reps: 5, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  typewriter_pullup: {
    exerciseId: 'typewriter_pullup',
    parent: 'explosive_pullup',
    children: ['archer_pullup'],
    unlockCriteria: { minReps: 5 },
    masteryThreshold: { reps: 3, consecutiveSessions: 4, difficultyTag: 'good' },
  },
  pushup: {
    exerciseId: 'pushup',
    parent: 'incline_pushup',
    children: ['diamond_pushup', 'decline_pushup'],
    unlockCriteria: { minReps: 5 },
    masteryThreshold: { reps: 20, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  diamond_pushup: {
    exerciseId: 'diamond_pushup',
    parent: 'pushup',
    children: ['archer_pushup'],
    unlockCriteria: { minReps: 15 },
    masteryThreshold: { reps: 15, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  archer_pushup: {
    exerciseId: 'archer_pushup',
    parent: 'diamond_pushup',
    children: ['pseudo_planche_pushup'],
    unlockCriteria: { minReps: 10 },
    masteryThreshold: { reps: 8, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  pike_pushup: {
    exerciseId: 'pike_pushup',
    children: ['elevated_pike_pushup'],
    unlockCriteria: {},
    masteryThreshold: { reps: 10, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  elevated_pike_pushup: {
    exerciseId: 'elevated_pike_pushup',
    parent: 'pike_pushup',
    children: ['handstand_wall_hold'],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { reps: 8, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  bodyweight_squat: {
    exerciseId: 'bodyweight_squat',
    children: ['bulgarian_split_squat', 'jump_squat'],
    unlockCriteria: {},
    masteryThreshold: { reps: 20, consecutiveSessions: 3, difficultyTag: 'easy' },
  },
  bulgarian_split_squat: {
    exerciseId: 'bulgarian_split_squat',
    parent: 'bodyweight_squat',
    children: ['assisted_pistol'],
    unlockCriteria: { minReps: 10 },
    masteryThreshold: { reps: 12, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  assisted_pistol: {
    exerciseId: 'assisted_pistol',
    parent: 'bulgarian_split_squat',
    children: ['pistol_squat'],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { reps: 5, consecutiveSessions: 4, difficultyTag: 'good' },
  },
  pistol_squat: {
    exerciseId: 'pistol_squat',
    parent: 'assisted_pistol',
    children: [],
    unlockCriteria: { minReps: 3 },
    masteryThreshold: { reps: 5, consecutiveSessions: 4, difficultyTag: 'good' },
  },
  plank: {
    exerciseId: 'plank',
    children: ['hollow_hold'],
    unlockCriteria: {},
    masteryThreshold: { duration: 60, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  hollow_hold: {
    exerciseId: 'hollow_hold',
    parent: 'plank',
    children: ['hanging_knee_raise'],
    unlockCriteria: { minDuration: 20 },
    masteryThreshold: { duration: 30, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  hanging_knee_raise: {
    exerciseId: 'hanging_knee_raise',
    parent: 'hollow_hold',
    children: ['hanging_leg_raise'],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { reps: 15, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  hanging_leg_raise: {
    exerciseId: 'hanging_leg_raise',
    parent: 'hanging_knee_raise',
    children: ['lsit'],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { reps: 12, consecutiveSessions: 3, difficultyTag: 'good' },
  },
  lsit: {
    exerciseId: 'lsit',
    parent: 'hanging_leg_raise',
    children: [],
    unlockCriteria: { minReps: 8 },
    masteryThreshold: { duration: 10, consecutiveSessions: 4, difficultyTag: 'good' },
  },
};
